### ISSUE TITLE
No sent data displayed.

### ISSUE THREAD

**Issue by Giger22** [elesiuta/picosnitch#35] opened 2023-12-03 19:44 UTC
![image](https://github.com/elesiuta/picosnitch/assets/120770420/87ca77fa-13c8-4aa1-bdec-c4cbb92c6201)

**Comment by elesiuta** [comment] 2023-12-11 23:19
Is this just with the UI, or is there nothing being logged at all for sent data? I'm not sure what would cause this, since the code for both is nearly identical, they're just kprobes for sock_sendmsg and sock_recvmsg.

Does this still happen after a restart? What kernel version are you on? Which version of bcc is installed? Is there anything in `~/.config/picosnitch/error.log`? Do you see any errors if you run picosnitch using `picosnitch start-no-daemon` instead?

Thanks!

**Comment by Giger22** [comment] 2023-12-12 13:54
There is no error.log file. I checked a snitch.db file and there are only 0s for a sent data column.

**Comment by elesiuta** [comment] 2023-12-12 21:32
I'm not able to reproduce this, which distro and kernel are you using?

Also which version of bcc are you using? you can check with `python3 -c "import bcc; print(bcc.__version__)"`

**Comment by Giger22** [comment] 2023-12-14 07:41
Artix Linux 6.6.4-artix-1-1 64 bit
python3 -c "import bcc; print(bcc.__version__)"
0.28.0

**Comment by elesiuta** [comment] 2023-12-14 10:33
Thanks, I can confirm this was caused specifically by something that changed between kernels 6.5 and 6.6.

I'm not sure when I'll have a chance to take a closer look at it, but if you'd like to take a stab at fixing it, it looks like the problem is in the bpf code. The text for it is stored in the variable `bpf_text_bandwidth_probe` at the bottom of the script, where the probe for sent and received is nearly identical, only difference being `sock_sendmsg` does not have the argument `int flags`. In the python part of the code, the callback `queue_sendv4_event` does not see any events at all.

**Comment by elesiuta** [comment] 2023-12-14 18:23
I did a bit of testing and it looks like we can no longer attach a kprobe at all to sock_sendmsg in 6.6, but inet_sendmsg and inet6_sendmsg work.

**Comment by elesiuta** [comment] 2023-12-14 18:50
I just pushed a change where sent data is now seen by using inet instead of sock, but it could use some testing to make sure all traffic is still being accounted for.

I also haven't looked into whether this is the best fix, or if there is something better that could be done, and what exactly happened to sock_sendmsg with the kernel and whether it was intentional or not.

**Comment by elesiuta** [comment] 2024-01-02 21:08
Released with 1.0.3

**Closed by elesiuta** 2024-01-02 21:08 UTC
