### ISSUE TITLE
Too much notification

### ISSUE THREAD

**Issue by pegasusearl** [elesiuta/picosnitch#14] opened 2022-03-11 03:36 UTC
This is a video of extreme case:
https://youtu.be/pYR2W7_bsjQ

Sometimes firefox also send some repetitive notifications.

I think a cooldown timer for each app or an options to disable notification entirely would be nice.

I can't manually disable notification as it's not listed in gnome settings > notification.

**Comment by pegasusearl** [comment] 2022-03-15 13:59
Hello, I'm sorry I can't confirm if the bug is fixed anymore since I have no way of reproducing it.

While I haven't update picosnitch, I tried to run the program again but looks like it does not happen anymore. I suspect it only happened when my internet had some strange issue.

Now I already updated picosnitch.

**Comment by elesiuta** [comment] 2022-03-15 15:24
No worries, thanks for trying and letting me know!

I'll close this issue since I am pretty sure the update will have fixed the root cause of the notifications, or at minimum reduce it to just one notification if it does happen again. Feel free to reopen this issue or create a new one if it happens again.

**Closed by elesiuta** 2022-03-15 15:24 UTC
